export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';

export const CARTITEMS_LOADING = 'CARTITEMS_LOADING';
export const CARTITEMS_FAILED = 'CARTITEMS_FAILED';
export const ADD_CARTITEMS = 'ADD_CARTITEMS';

export const HOMEPAGES_LOADING = 'HOMEPAGES_LOADING';
export const HOMEPAGES_FAILED = 'HOMEPAGES_FAILED';
export const ADD_HOMEPAGES = 'ADD_HOMEPAGES';

export const DECORS_LOADING = 'DECORS_LOADING';
export const DECORS_FAILED = 'DECORS_FAILED';
export const ADD_DECORS = 'ADD_DECORS';

export const AUTOMOTIVES_LOADING = 'AUTOMOTIVES_LOADING';
export const AUTOMOTIVES_FAILED = 'AUTOMOTIVES_FAILED';
export const ADD_AUTOMOTIVES = 'ADD_AUTOMOTIVES';

export const ELECTRONICS_LOADING = 'ELECTRONICS_LOADING';
export const ELECTRONICS_FAILED = 'ELECTRONICS_FAILED';
export const ADD_ELECTRONICS = 'ADD_ELECTRONICS';

export const FASHIONS_LOADING = 'FASHIONS_LOADING';
export const FASHIONS_FAILED = 'FASHIONS_FAILED';
export const ADD_FASHIONS = 'ADD_FASHIONS';

export const OUTDOORS_LOADING = 'OUTDOORS_LOADING';
export const OUTDOORS_FAILED = 'OUTDOORS_FAILED';
export const ADD_OUTDOORS = 'ADD_OUTDOORS';

export const PETS_LOADING = 'PETS_LOADING';
export const PETS_FAILED = 'PETS_FAILED';
export const ADD_PETS = 'ADD_PETS';